language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer update --prefer-source --no-interaction --prefer-stable
  - sudo gem install mailcatcher

before_script:
  - touch tests/database.sqlite
  - php artisan vendor:publish --env="testing" --provider="\Appkr\Fractal\ApiServiceProvider"
  - php artisan migrate --env="testing" --database="sqlite"
  - php artisan db:seed --env="testing" --database="sqlite"
  - sed -i "s/\/\/ $this->publishExamples();/$this->publishExamples();/" vendor/appkr/fractal/src/ApiServiceProvider.php;
  - mailcatcher

script: vendor/bin/phpunit

matrix:
  fast_finish: true