language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - DB_CONNECTION=sqlite

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source --no-scripts --dev
  - travis_retry gem install mailcatcher

before_script:
  - touch tests/database.sqlite
  - cp .env.example .env
  - php artisan clear-compiled
  - php artisan optimize
  - php artisan migrate --env="testing" --database="sqlite" --force
  - php artisan db:seed --env="testing" --database="sqlite" --force
  - mailcatcher

script: vendor/bin/phpunit

matrix:
  fast_finish: true